/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recrutamentointerno_correcao;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.URL;
import java.net.URLConnection;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Emerson Jr.
 */
public class TelaPrincipalCEP extends javax.swing.JFrame {

  private Connection connection;

  private DefaultTableModel tableModel;

  /** Creates new form TelaPrincipalCEP */
  public TelaPrincipalCEP() {
    initComponents();

    tableModel = new DefaultTableModel(new String[]{"CEP", "Logradouro"}, 0);

    table.setModel(tableModel);

    try {
      this.connection = DriverManager.getConnection(
          "jdbc:mysql://localhost:9000/ri?user=root&password=senharoot");

      PreparedStatement preparedStatement = connection.
          prepareStatement("select * from ri.historico");

      ResultSet rs = null;
      try {
        rs = preparedStatement.executeQuery();

        while (rs.next()) {
          tableModel.addRow(
              new Object[]{rs.getString("cep"), rs.getString("resultado")});
        }
      }
      catch (Exception ex) {
        if (rs != null) {
          rs.close();
        }
      }

    }
    catch (Exception ex) {
      JOptionPane.showMessageDialog(this,
          "Falha ao conectar no BD: \n" + ex.getMessage(),
          "Falha de BD",
          JOptionPane.ERROR_MESSAGE);
    }
  }

 

  private Logradouro consultaCEP(String cep) throws Exception {

    URL url = new URL("https://viacep.com.br/ws/" + cep + "/json");
    URLConnection urlConnection = url.openConnection();

    InputStream is = urlConnection.getInputStream();
    BufferedReader bff = new BufferedReader(new InputStreamReader(is));

    StringBuilder sb = new StringBuilder();

    bff.lines().forEach(l -> sb.append(l.trim()));
    String json = sb.toString();

    ObjectMapper objectMapper = new ObjectMapper();
    Logradouro logradouro = objectMapper.readValue(json, Logradouro.class);

    if (logradouro.isErro()) {
      throw new Exception("Logradouro não encontrado!");
    }

    return logradouro;
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    labelCEP = new javax.swing.JLabel();
    textCEP = new javax.swing.JTextField();
    buttonProcurar = new javax.swing.JButton();
    labelLogradouro = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    textPanelLogradouro = new javax.swing.JTextPane();
    labelHistorico = new javax.swing.JLabel();
    jScrollPane2 = new javax.swing.JScrollPane();
    table = new javax.swing.JTable();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    labelCEP.setText("CEP:");

    textCEP.setColumns(15);
    textCEP.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        textCEPActionPerformed(evt);
      }
    });

    buttonProcurar.setText("Procurar");
    buttonProcurar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buttonProcurarActionPerformed(evt);
      }
    });

    labelLogradouro.setText("Logradouro:");

    jScrollPane1.setViewportView(textPanelLogradouro);

    labelHistorico.setText("Historico De Pesquisa");

    table.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null},
        {null, null},
        {null, null},
        {null, null}
      },
      new String [] {
        "CEP", "Logradouro"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.String.class, java.lang.String.class
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }
    });
    jScrollPane2.setViewportView(table);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(21, 21, 21)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(labelLogradouro)
          .addComponent(labelCEP))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(textCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(buttonProcurar))
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(0, 39, Short.MAX_VALUE))
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(labelHistorico)
          .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(17, 17, 17)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(labelCEP)
          .addComponent(textCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(buttonProcurar))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(labelLogradouro)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(labelHistorico)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void textCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCEPActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_textCEPActionPerformed

  private void buttonProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProcurarActionPerformed

    try {
      String cep = textCEP.getText();

      //cep = cep.replaceAll("[^0-9]", "");

      for (char c : cep.toCharArray()) {
        if (c < '0' || c > '9') {
          JOptionPane.showMessageDialog(this,
              "Cep com chars inválidos: " + cep,
              "Falha de CEP",
              JOptionPane.ERROR_MESSAGE);

          return;
        }
      }

      if (cep.length() != 8) {
        JOptionPane.showMessageDialog(this,
            "Cep inválido: " + cep,
            "Falha de CEP",
            JOptionPane.ERROR_MESSAGE);

        return;
      }

      Logradouro logradouro = consultaCEP(cep);

      String textoLogradouro = String.format("Rua %s, Cidade %s, Estado %s",
          logradouro.getLogradouro(),
          logradouro.getLocalidade(),
          logradouro.getUf());

      textPanelLogradouro.setText(textoLogradouro);


      if (connection != null) {
        PreparedStatement preparedStatement = connection.
            prepareStatement("insert into ri.historico (cep, resultado) values (?,?)");

        preparedStatement.setString(1, cep);
        preparedStatement.setString(2, textoLogradouro);

        preparedStatement.execute();
      }


      tableModel.addRow(new Object[]{cep, textoLogradouro});
    }
    catch (Exception ex) {
      JOptionPane.showMessageDialog(this,
          "Falha procurar CEP: \n" + ex.getMessage(),
          "Falha de CEP",
          JOptionPane.ERROR_MESSAGE);
    }


  }//GEN-LAST:event_buttonProcurarActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(TelaPrincipalCEP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(TelaPrincipalCEP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(TelaPrincipalCEP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(TelaPrincipalCEP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {

      public void run() {
        new TelaPrincipalCEP().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  protected javax.swing.JButton buttonProcurar;
  protected javax.swing.JScrollPane jScrollPane1;
  protected javax.swing.JScrollPane jScrollPane2;
  protected javax.swing.JLabel labelCEP;
  protected javax.swing.JLabel labelHistorico;
  protected javax.swing.JLabel labelLogradouro;
  protected javax.swing.JTable table;
  protected javax.swing.JTextField textCEP;
  protected javax.swing.JTextPane textPanelLogradouro;
  // End of variables declaration//GEN-END:variables

}
